import { dirname, join } from "node:path";
import type { AgentSetupInput, Profile } from "../shared/types.ts";
import { piProfileControls } from "./pi-profile-controls.ts";

export const shellQuote = (value: string) =>
  `'${value.replaceAll("'", "'\\''")}'`;

function claudeModelEnvironment() {
  return {
    CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY: "1",
    CLAUDE_CODE_USE_BEDROCK: "0",
    CLAUDE_CODE_USE_VERTEX: "0",
    CLAUDE_CODE_USE_FOUNDRY: "0",
    CLAUDE_CODE_USE_MANTLE: "0",
    CLAUDE_CODE_USE_ANTHROPIC_AWS: "0",
    ANTHROPIC_CUSTOM_HEADERS: "",
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: "1",
  };
}

// Called by the harness's native credential hook, never as an agent launcher.
// The installed URL stays fixed; a port change must fail before returning a key.
export function credentialHelper(
  profile: Profile,
  socket: string,
  port: number,
): string {
  return `#!/bin/sh
set -eu
nv_connection=$(curl -q --fail --silent --show-error --noproxy '*' --proxy '' --max-time 4 --unix-socket ${shellQuote(socket)} ${shellQuote(`http://localhost/profiles/${profile.id}`)}) || {
  printf '%s\\n' ${shellQuote(`Open nonstopvibin and start ${profile.slug}.`)} >&2
  exit 1
}
nv_key=\${nv_connection%%'
'*}
nv_port=\${nv_connection#*'
'}
case "$nv_key" in nv_*) ;; *) exit 1 ;; esac
case "$nv_key" in *[!a-zA-Z0-9_-]*) exit 1 ;; esac
[ "\${#nv_key}" -eq 46 ] || exit 1
[ "$nv_port" = ${shellQuote(String(port))} ] || {
  printf '%s\\n' 'The gateway port changed. Reconnect this agent in nonstopvibin.' >&2
  exit 1
}
printf '%s\\n' "$nv_key"
`;
}

export function nativeProvider(profile: Profile): string {
  return `nonstopvibin-${profile.slug}`;
}

export function nativeConfiguration(
  profile: Profile,
  input: AgentSetupInput,
  helper: string,
  port: number,
): string {
  const provider = nativeProvider(profile);
  const endpoint = `http://127.0.0.1:${port}/p/${profile.slug}/v1`;
  if (input.agent === "codex")
    return `# Generated by nonstopvibin. Select with codex --profile nonstopvibin-${profile.slug}.
model_provider = ${JSON.stringify(provider)}

[model_providers.${provider}]
name = ${JSON.stringify(`nonstopvibin · ${profile.name}`)}
base_url = ${JSON.stringify(endpoint)}
wire_api = "responses"${
      input.otherProviders === false
        ? `\nhttp_headers = { "x-nonstopvibin-agent" = "codex" }`
        : ""
    }

[model_providers.${provider}.auth]
command = ${JSON.stringify(helper)}
timeout_ms = 5000
refresh_interval_ms = 300000
`;
  if (input.agent === "claude")
    return JSON.stringify({
      apiKeyHelper: shellQuote(helper),
      env: {
        ...claudeModelEnvironment(),
        ANTHROPIC_BASE_URL: endpoint.replace(/\/v1$/, ""),
        ANTHROPIC_AUTH_TOKEN: "",
        ANTHROPIC_API_KEY: "",
        CLAUDE_CODE_OAUTH_TOKEN: "",
        CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR: "",
      },
    });
  return `// Generated by nonstopvibin. Refresh the complete profile catalog at startup or /reload.
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { getBuiltinModel } from "@earendil-works/pi-ai/providers/all";
// pi's own catalog knows these vendors' names, thinking levels, and quirks.
const builtin = { "anthropic-messages": "anthropic", "openai-responses": "openai" };
${piProfileControls}
export default async function (pi) {
  let models = [];
  try {
    const { stdout } = await promisify(execFile)(${JSON.stringify(helper)}, [], { timeout: 10000, maxBuffer: 128 });
    const key = stdout.trim();
    if (!/^nv_[A-Za-z0-9_-]{43}$/.test(key)) throw new Error("Invalid nonstopvibin credential.");
    const response = await fetch(${JSON.stringify(`${endpoint}/models?nonstopvibin=pi`)}, {
      headers: { Authorization: "Bearer " + key }, redirect: "error", signal: AbortSignal.timeout(30000)
    });
    if (!response.ok) throw new Error("Could not refresh nonstopvibin models. Open Connect agents and check this profile's catalog.");
    ({ models } = await response.json());
    if (!Array.isArray(models) || !models.length) throw new Error("The nonstopvibin catalog is empty.");
    models = models.map((model) => {
      const { provider, headers, compat, ...known } = getBuiltinModel(builtin[model.api], model.id) ?? {};
      // Keep pi's effort fallback; native tool changes use the builtin model's capabilities.
      return { ...model, ...known, compat: { ...compat, supportsMidConvoEffort: false }, api: model.api, baseUrl: model.api === "anthropic-messages" ? ${JSON.stringify(endpoint.replace(/\/v1$/, ""))} : ${JSON.stringify(endpoint)} };
    });
    pi.registerProvider(${JSON.stringify(provider)}, {
      name: printable(${JSON.stringify(profile.name)}), baseUrl: ${JSON.stringify(endpoint)}, apiKey: ${JSON.stringify(`!${shellQuote(helper)}`)},
      models,
    });
  } catch {
    pi.on("session_start", (_event, ctx) => {
      // During extension loading unregisterProvider only cancels pending registrations.
      pi.unregisterProvider(${JSON.stringify(provider)});
      ctx.ui.notify(printable(${JSON.stringify(`Could not load ${profile.name}'s nonstopvibin models. The profile may be stopped, deleted, or have no available models. Check Connect agents and reconnect, then /reload. Use /nv to choose another profile.`)}), "warning");
    });
  }
  connectProfileControls(pi, ${JSON.stringify({ provider, name: profile.name, slug: profile.slug })}, ${JSON.stringify(join(dirname(dirname(helper)), "pi-preferences"))});
}
`;
}
